[package]
name = "bevy_aoui_widgets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ab_glyph = "0.2.23"
arboard = { version = "3.2.1", default-features = false }
bevy = { version = "^0.12", default-features = false, features = ["bevy_sprite", "bevy_text"] }
bevy_aoui = {version = "^0.1", path = "../aoui"}
bevy_prototype_lyon = "^0.10.0"
colorthis = "^0.1.1"
string_iter = "0.1.0"
