[package]
name = "bevy_aoui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "^0.11"
colorthis = "^0.1.1"
bevy-aoui-derive = { path = "../derive" }


[features]
default = ["bundles", "ui"]
## Enable ui features and macro based DSL
ui = []
## Enable alternative versions of bevy's sprite, spritesheet and text bundles.
bundles = []

[dev-dependencies]
rand = "0.8.5"
